In [1]:
import h5py

import numpy as np

from ase.build import molecule
from ase.io.proteindatabank import read_proteindatabank
from ase.io.sdf import read_sdf

In [2]:
f= h5py.File('OCH.h5', 'r')

In [114]:
list(f.keys())

['103923944',
 '103932169',
 '103935718',
 '103946401',
 '103951197',
 '103955658',
 '103958296',
 '103986070',
 '103987724',
 '103988754',
 '103989125',
 '103989618',
 '103992457',
 '104000591',
 '104000618',
 '104010529',
 '104035148',
 '104039420',
 '104049795',
 '104051449',
 '104054545',
 '104059734',
 '104060354',
 '104065551',
 '104073658',
 '104076888',
 '104085518',
 '104087858',
 '104089703',
 '104098841',
 '104098844',
 '104098954',
 '104098991',
 '104103266',
 '104109903',
 '104118585',
 '104118994',
 '104119443',
 '104119804',
 '104122671',
 '104132449',
 '104142655',
 '104151795',
 '104157506',
 '104158321',
 '125082293',
 '125082841',
 '125084169',
 '134973225',
 '134973378',
 '134975164',
 '134975581',
 '134977752',
 '134978065',
 '134978584',
 '134979308',
 '134982715',
 '134983764',
 '134984031',
 '134984686',
 '134984753',
 '134984847',
 '134985895',
 '134987745',
 '134992793',
 '134993187',
 '134993910',
 '134994477',
 '134995215',
 '134995396',
 '134995747',
 '1349

In [115]:
dir(f)

['_MutableMapping__marker',
 '__abstractmethods__',
 '__bool__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__nonzero__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_d',
 '_e',
 '_gcpl_crt_order',
 '_id',
 '_ipython_key_completions_',
 '_lapl',
 '_lcpl',
 '_libver',
 'attrs',
 'build_virtual_dataset',
 'clear',
 'close',
 'copy',
 'create_dataset',
 'create_dataset_like',
 'create_group',
 'create_virtual_dataset',
 'driver',
 'file',
 'filename',
 'flush',
 'get',
 'id',
 'items',
 'keys',
 'libver',
 'mode'

In [117]:
f['103923944'].keys()

<KeysViewHDF5 ['atomic_numbers', 'conformations', 'dft_total_energy', 'dft_total_gradient', 'formation_energy', 'mayer_indices', 'mbis_charges', 'mbis_dipoles', 'mbis_octupoles', 'mbis_quadrupoles', 'scf_dipole', 'scf_quadrupole', 'smiles', 'subset', 'wiberg_lowdin_indices']>

In [ ]:
f.close()

## Setting up ASE initial conformations

### Ethanol

In [65]:
ethanol= molecule('CH3CH2OH') # create from the database

In [69]:
dir(ethanol)

['__add__',
 '__class__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_ase_handles_dynamic_stress',
 '_calc',
 '_celldisp',
 '_cellobj',
 '_centering_as_array',
 '_constraints',
 '_del_constraints',
 '_get_atomic_numbers',
 '_get_constraints',
 '_get_positions',
 '_masked_rotate',
 '_pbc',
 '_set_positions',
 'append',
 'arrays',
 'ase_objtype',
 'calc',
 'cell',
 'center',
 'constraints',
 'copy',
 'edit',
 'euler_rotate',
 'extend',
 'fromdict',
 'get_all_distances',
 'get_angle',
 'get_angles',
 'get_angular_momentum',
 'get_array',
 'get_atomic_numbers',
 'get_calculator',
 'get_c

In [76]:
ethanol.get_all_distances()

array([[0.        , 1.51193497, 2.36458006, 3.21144555, 2.15383142,
        2.15383142, 1.09333328, 1.09175654, 1.09175654],
       [1.51193497, 0.        , 1.42684013, 1.95473852, 1.0992838 ,
        1.0992838 , 2.15613991, 2.1466157 , 2.1466157 ],
       [2.36458006, 1.42684013, 0.        , 0.97132389, 2.08944599,
        2.08944599, 3.32689003, 2.61083643, 2.61083643],
       [3.21144555, 1.95473852, 0.97132389, 0.        , 2.32932075,
        2.32932075, 4.06940521, 3.50066459, 3.50066459],
       [2.15383142, 1.0992838 , 2.08944599, 2.32932075, 0.        ,
        1.773866  , 2.49293247, 2.49366296, 3.05961163],
       [2.15383142, 1.0992838 , 2.08944599, 2.32932075, 1.773866  ,
        0.        , 2.49293247, 3.05961163, 2.49366296],
       [1.09333328, 2.15613991, 3.32689003, 4.06940521, 2.49293247,
        2.49293247, 0.        , 1.7767203 , 1.7767203 ],
       [1.09175654, 2.1466157 , 2.61083643, 3.50066459, 2.49366296,
        3.05961163, 1.7767203 , 0.        , 1.771762  ],


In [75]:
ethanol.get_all_distances().shape

(9, 9)

In [79]:
ethanol.get_calculator()

In [81]:
ethanol.positions

array([[ 1.168181, -0.400382,  0.      ],
       [ 0.      ,  0.559462,  0.      ],
       [-1.190083, -0.227669,  0.      ],
       [-1.946623,  0.381525,  0.      ],
       [ 0.042557,  1.207508,  0.886933],
       [ 0.042557,  1.207508, -0.886933],
       [ 2.115891,  0.1448  ,  0.      ],
       [ 1.128599, -1.037234,  0.885881],
       [ 1.128599, -1.037234, -0.885881]])

### Malonaldehyde

In [111]:
malonaldehyde= read_sdf('Malonaldehyde.sdf')

In [103]:
dir(malonaldehyde)

['__add__',
 '__class__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_ase_handles_dynamic_stress',
 '_calc',
 '_celldisp',
 '_cellobj',
 '_centering_as_array',
 '_constraints',
 '_del_constraints',
 '_get_atomic_numbers',
 '_get_constraints',
 '_get_positions',
 '_masked_rotate',
 '_pbc',
 '_set_positions',
 'append',
 'arrays',
 'ase_objtype',
 'calc',
 'cell',
 'center',
 'constraints',
 'copy',
 'edit',
 'euler_rotate',
 'extend',
 'fromdict',
 'get_all_distances',
 'get_angle',
 'get_angles',
 'get_angular_momentum',
 'get_array',
 'get_atomic_numbers',
 'get_calculator',
 'get_c

In [104]:
malonaldehyde.get_positions()

array([[ 1.3685e+00,  8.9020e-01,  2.2000e-03],
       [-1.3685e+00,  8.9020e-01,  2.2000e-03],
       [-1.0000e-04, -1.1149e+00,  6.9000e-03],
       [ 1.2852e+00, -3.3280e-01, -5.7000e-03],
       [-1.2852e+00, -3.3280e-01, -5.6000e-03],
       [ 0.0000e+00, -1.7434e+00,  9.0280e-01],
       [-1.0000e-04, -1.7651e+00, -8.7350e-01],
       [ 2.2008e+00, -9.4940e-01, -1.7800e-02],
       [-2.2008e+00, -9.4930e-01, -1.7600e-02]])

### Aspirin

In [112]:
aspirin= read_sdf('Aspirin.sdf')

In [155]:
aspirin

Atoms(symbols='O4C9H8', pbc=False)

In [106]:
dir(aspirin)

['__add__',
 '__class__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_ase_handles_dynamic_stress',
 '_calc',
 '_celldisp',
 '_cellobj',
 '_centering_as_array',
 '_constraints',
 '_del_constraints',
 '_get_atomic_numbers',
 '_get_constraints',
 '_get_positions',
 '_masked_rotate',
 '_pbc',
 '_set_positions',
 'append',
 'arrays',
 'ase_objtype',
 'calc',
 'cell',
 'center',
 'constraints',
 'copy',
 'edit',
 'euler_rotate',
 'extend',
 'fromdict',
 'get_all_distances',
 'get_angle',
 'get_angles',
 'get_angular_momentum',
 'get_array',
 'get_atomic_numbers',
 'get_calculator',
 'get_c

In [107]:
aspirin.get_positions()

array([[ 1.2333,  0.554 ,  0.7792],
       [-0.6952, -2.7148, -0.7502],
       [ 0.7958, -2.1843,  0.8685],
       [ 1.7813,  0.8105, -1.4821],
       [-0.0857,  0.6088,  0.4403],
       [-0.7927, -0.5515,  0.1244],
       [-0.7288,  1.8464,  0.4133],
       [-2.1426, -0.4741, -0.2184],
       [-2.0787,  1.9238,  0.0706],
       [-2.7855,  0.7636, -0.2453],
       [-0.1409, -1.8536,  0.1477],
       [ 2.1094,  0.6715, -0.3113],
       [ 3.5305,  0.5996,  0.1635],
       [-0.1851,  2.7545,  0.6593],
       [-2.7247, -1.3605, -0.4564],
       [-2.5797,  2.8872,  0.0506],
       [-3.8374,  0.8238, -0.509 ],
       [ 3.729 ,  1.4184,  0.8593],
       [ 4.2045,  0.6969, -0.6924],
       [ 3.7105, -0.3659,  0.6426],
       [-0.2555, -3.5916, -0.7337]])

In [110]:
aspirin.get_number_of_atoms()

C:\Users\harma\anaconda3\envs\mlmp\lib\site-packages\ase\atoms.py:967: VisibleDeprecationWarning: Use get_global_number_of_atoms() instead
  warnings.warn('Use get_global_number_of_atoms() instead',


21